[[plugins]]
repo = 'junegunn/fzf'
if = 'executable("fzf")'
on_cmd = ['FZF','fzf#run']

[[plugins]] # 補完
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_add = '''
  " <TAB> で補完を選択
  inoremap <silent><expr> <Tab> pumvisible() ? "\<C-n>" : deoplete#mappings#manual_complete()
'''
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]] # Codic
repo = 'koron/codic-vim'
on_cmd = 'Codic'

[[plugins]] # Emmet
repo = 'mattn/emmet-vim'
on_i = 1
hook_source = '''
  let g:user_emmet_mode = 'i'
  let g:user_emmet_leader_key='<C-E>'
  let g:use_emmet_complete_tag = 1
  let g:user_emmet_settings = {
  \   'variables': {
  \     'lang': "ja"
  \   },
  \   'indentation': '    '
  \ }
'''

[[plugins]] # EditorConfig
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'