[[plugins]]
repo = 'Shougo/dein.vim'

# Lang {{{

# Haml
[[plugins]]
repo  = 'tpope/vim-haml'
on_ft = 'haml'

# Html5
[[plugins]]
repo  = 'othree/html5.vim'
on_ft = 'html'

# Toml
[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

# Markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
'''

# Golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

# TMUX
[[plugins]]
repo = 'tmux-plugins/vim-tmux'
on_ft = 'tmux'

# Japanese doc
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

# }}}
# Colors {{{

# hybrid
[[plugins]]
repo = 'w0ng/vim-hybrid'

# solarized
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'colepeters/vim-hybrid-material'

# }}}
# ---

# ステータスライン
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = { 'colorscheme': 'wombat' }
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  let g:openbrowser_menu_lang = 'ja'
'''

[[plugins]]
repo = 'tell-k/vim-browsereload-mac'
if = 'has("mac")'

# ---

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_add = '''
  if executable('pt')
    let g:unite_source_grep_command = 'pt'
    let g:unite_source_grep_default_opts = '--nogroup --nocolor'
    let g:unite_source_grep_recursive_opt = ''
  endif
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_add = '''
  let g:vimfiler_as_default_explorer=1
  let g:vimfiler_safe_mode_by_default = 0
  " Like Textmate icons.
  let g:vimfiler_tree_leaf_icon = ' '
  let g:vimfiler_tree_opened_icon = '▾'
  let g:vimfiler_tree_closed_icon = '▸'
  let g:vimfiler_file_icon = '-'
  let g:vimfiler_marked_file_icon = '*'
  nnoremap <C-X>f :<C-u>VimFiler -split -simple -winwidth=35 -no-quit<CR>
'''
