[[plugins]]
repo = 'Shougo/dein.vim'

# ---

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = { 
  \   'colorscheme': 'wombat'
  \ }
'''

# Colors

[[plugins]] # hybrid
repo = 'w0ng/vim-hybrid'

[[plugins]] # solarized
repo = 'altercation/vim-colors-solarized'

# Lang

[[plugins]] # Haml
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
'''

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # TMUX
repo = 'tmux-plugins/vim-tmux'
on_ft = 'tmux'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

# Test

[[plugins]] # Git
repo = 'tpope/vim-fugitive'
on_cmd = ['Gwrite','Gcommit','Gread','Gstatus','Gdiff','Gblame']

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  let g:openbrowser_menu_lang = 'ja'
'''

[[plugins]]
repo = 'tell-k/vim-browsereload-mac'
if = 'has("mac")'