[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo  = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo  = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

# Japanese doc
[[plugins]]
repo  = 'vim-jp/vimdoc-ja'
on_ft = 'help'

# カラースキーマ

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'w0ng/vim-hybrid'
