[[plugins]]
repo = 'zchee/nvim-go'
name = 'neogo'
if = 'executable("bg")'
build = 'make'
on_source = 'go'
hook_source = '''
	let g:go#build#autobuild = 1
'''

[[plugins]]
repo = 'neomake/neomake'
on_cmd = 'Neomake'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'

# 補完 {{{

[[plugins]] # Auto Close (括弧)
repo = 'Shougo/neopairs.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
depends = ['context_filetype', 'neopairs']
on_event = 'InsertEnter'
hook_source = '''
	" <TAB>: completion.
	imap <silent><expr> <TAB> pumvisible() ? "\<C-n>" : <SID>check_back_space() ? "\<TAB>" : deoplete#mappings#manual_complete()
	function! s:check_back_space() abort
		let col = col('.') - 1
		return !col || getline('.')[col - 1]  =~ '\s'
	endfunction

	" <S-TAB>: completion back.
	inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<C-h>"

	" <CR>: close popup and save indent.
	inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
	function! s:my_cr_function() abort
	  return deoplete#close_popup() . "\<CR>"
	endfunction

	let g:deoplete#enable_at_startup = 1
	let g:deoplete#enable_ignore_case = 1
	let g:deoplete#enable_smart_case = 1
'''

[[plugins]]
repo = 'wellle/tmux-complete.vim'
if = 'executable("tmux")'
depends = 'deoplete'
on_source = 'deoplete'
hook_source = '''
	let g:tmuxcomplete#trigger = ""
'''

[[plugins]] # Golang
repo = 'zchee/deoplete-go'
if = 'executable("go")'
depends = 'deoplete'
on_ft = 'go'
build = 'make'
hook_source = '''
	let g:deoplete#sources#go#use_cache = 1
	let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
	let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
'''

[[plugins]] # Vim
repo = 'Shougo/neco-vim'
depends = 'deoplete'
on_ft = 'vim'

[[plugins]] # Zsh
repo = 'zchee/deoplete-zsh'
depends = 'deoplete'
on_ft = 'zsh'

# }}}
# Denite {{{

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("python3")'
on_cmd = 'Denite'
hook_post_source = '''
	" file_mru
	call denite#custom#source('file_mru', 'matchers', ['matcher_fuzzy', 'matcher_project_files'])
	call denite#custom#source('file_mru', 'converters', ['converter_relative_word'])

	" file_rec
	if executable('rg')
		call denite#custom#var('file_rec', 'command', ['rg', '--files', '--hidden', '--glob', '!.git'])
	elseif executable('pt')
		call denite#custom#var('file_rec', 'command', ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
	elseif executable('ag')
		" https://git.io/vPEZA
		call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
	endif

	" grep
	if executable('rg')
		" https://git.io/vPEZP
		call denite#custom#var('grep', 'command', ['rg'])
		call denite#custom#var('grep', 'recursive_opts', [])
		call denite#custom#var('grep', 'final_opts', [])
		call denite#custom#var('grep', 'separator', ['--'])
		call denite#custom#var('grep', 'default_opts', ['--vimgrep', '--no-heading'])
	elseif executable('pt')
		call denite#custom#var('grep', 'command', ['pt'])
		call denite#custom#var('grep', 'recursive_opts', [])
		call denite#custom#var('grep', 'default_opts', ['--nogroup', '--nocolor', '--smart-case', '--hidden'])
	endif

	" Define alias
	call denite#custom#alias('source', 'file_rec/git', 'file_rec')
	call denite#custom#var('file_rec/git', 'command', ['git', 'ls-files', '-co', '--exclude-standard'])

	" Change default prompt
	call denite#custom#option('default', 'prompt', '>')
'''

[[plugins]]
repo = 'nixprime/cpsm'
if = 'has("python3")'
build = 'PY3=ON ./install.sh'
on_source = 'denite'
hook_post_source = '''
	call denite#custom#source('file_rec', 'matchers', ['matcher_cpsm'])
	call denite#custom#source('grep', 'matchers', ['matcher_ignore_globs', 'matcher_cpsm'])
'''

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
if = 'executable("ghq")'
depends = 'denite'
on_cmd = 'DeniteGhq'
on_source = 'denite'

# }}}
